// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5isjM5V-TTI9TuO_IdQZf9LHStSaXBuY',
    appId: '1:846047103358:web:abad8efa51a04febf64b2f',
    messagingSenderId: '846047103358',
    projectId: 'tps-forms',
    authDomain: 'tps-forms.firebaseapp.com',
    storageBucket: 'tps-forms.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnfCpuobOr1luPPMbfV2Y5mxsMj6g4lt4',
    appId: '1:846047103358:android:c102bd67494a8a20f64b2f',
    messagingSenderId: '846047103358',
    projectId: 'tps-forms',
    storageBucket: 'tps-forms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCafzU2vjtD8RkuQgxO4LB8drjmLYTaeHE',
    appId: '1:846047103358:ios:7eabb20261fb7d23f64b2f',
    messagingSenderId: '846047103358',
    projectId: 'tps-forms',
    storageBucket: 'tps-forms.appspot.com',
    iosBundleId: 'com.example.formsTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCafzU2vjtD8RkuQgxO4LB8drjmLYTaeHE',
    appId: '1:846047103358:ios:378fe0856f5fcd48f64b2f',
    messagingSenderId: '846047103358',
    projectId: 'tps-forms',
    storageBucket: 'tps-forms.appspot.com',
    iosBundleId: 'com.example.formsTutorial.RunnerTests',
  );
}
